# Generated by Django 3.1 on 2024-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
